/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-10-04 05:49:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hanki;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>한끼맛있다</title>\r\n");
      out.write("<meta name=\"naver-site-verification\" content=\"fdb874a536daa44431e562983af2c160a76457cf\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"user-scalable=yes, initial-scale=1.0, maximum-scale=2.0, minimum-scale=0.5, width=device-width\">\r\n");
      out.write("<meta name=\"subject\" content=\"한끼맛있다\" />\r\n");
      out.write("<meta name=\"copyright\" content=\"(주)쉐프마인드\" />\r\n");
      out.write("<meta name=\"title\" content=\"한끼맛있다\" />\r\n");
      out.write("<meta name=\"description\" content=\"패밀리 퓨전레스토랑 프랜차이즈, 브랜드스토리, 메뉴소개 및 매장안내, 매장창업\" />\r\n");
      out.write("<link rel=\"canonical\" href=\"http://www.hankikor.com/\" />\r\n");
      out.write("<meta property=\"og:title\"           content=\"한끼맛있다\"/>\r\n");
      out.write("<meta property=\"og:site_name\"       content=\"(주)쉐프마인드\"/>\r\n");
      out.write("<meta property=\"og:type\"            content=\"website\"/>\r\n");
      out.write("<meta property=\"og:url\"             content=\"http://www.hankikor.com/main\"/>\r\n");
      out.write("<meta property=\"og:image\"           content=\"http://www.hankikor.com/thum_img/ehompy0118/og_img/og_logo1519610629.jpg\"/>\r\n");
      out.write("<meta property=\"og:description\"     content=\"패밀리 퓨전레스토랑 프랜차이즈, 브랜드스토리, 메뉴소개 및 매장안내, 매장창업\"/>\r\n");
      out.write("<meta name=\"twitter:card\"           content=\"summary\">\r\n");
      out.write("<meta name=\"twitter:title\"          content=\"한끼맛있다\">\r\n");
      out.write("<meta name=\"twitter:site\"           content=\"(주)쉐프마인드\">\r\n");
      out.write("<meta name=\"twitter:image\"          content=\"http://www.hankikor.com/thum_img/ehompy0118/og_img/og_logo1519610629.jpg\">\r\n");
      out.write("<meta name=\"twitter:description\"    content=\"패밀리 퓨전레스토랑 프랜차이즈, 브랜드스토리, 메뉴소개 및 매장안내, 매장창업\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./hanki/img/favicon_null.png\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/_addon/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./hanki/css/head_basic.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./hanki/css/head_logout.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\">var MOBILE_CONN_YN = false;</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/js/all_default.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var ios_yn = false;\r\n");
      out.write("var APP_CONN_YN = false;\r\n");
      out.write("var isKitkat = window.navigator.userAgent.search( \"AnybuildApp Android 4.4\") > -1 ? true : false;\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/navi_category_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/goods_category_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/board_list.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/site_category_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/gisa_category_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/etc/movie_category_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/js/all_default2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/js/google_map.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/js/load_frame.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/js/head_logout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" id='naver_map_js' ></script>\r\n");
      out.write("<script type=\"text/javascript\" id='dynamic_js' ></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/_addon/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<!---->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./hanki/img_up/_addon/css/reset_1.0.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./hanki/img_up/shop_pds/ehompy0118/src_css_fram/pc.skin.main.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/_addon/_plugin/modernizr/modernizr.custom.media.query.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./hanki/img_up/shop_pds/ehompy0118/src_css_fram/pc.main.44525.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./hanki/img_up/shop_pds/ehompy0118/design/owl.carousel.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/design/owl.carousel.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./hanki/img_up/shop_pds/ehompy0118/design/modernizr.custom.media.query.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("   var ssl_host = \"ssl.anybuild.co.kr\";\r\n");
      out.write("   var mall_id = \"ehompy0118\";\r\n");
      out.write("   var ssl_possible = 'on';   var LAN = \"kr\";\r\n");
      out.write("   var category = \"\";\r\n");
      out.write("   function start_page_set(){\r\n");
      out.write("      advertise_tmp.style.behavior='url(#default#HomePage)';\r\n");
      out.write("      advertise_tmp.setHomePage('http://www.hankikor.com');\r\n");
      out.write("   }\r\n");
      out.write("   function bookmark(){\r\n");
      out.write("      window.external.AddFavorite('http://www.hankikor.com', \"한끼맛있다\") ;\r\n");
      out.write("   }\r\n");
      out.write("   var page_title = \"한끼맛있다\";\r\n");
      out.write("   </script>\r\n");
      out.write("            <script>\r\n");
      out.write("         // AI-LOG 기본 스크립트\r\n");
      out.write("         var ai_log_user_key = \"\";  // 최초접속자 설정 키값 (default:null)\r\n");
      out.write("         var ai_log_account_id = \"ehompy0118\"; // AI-LOG 계정 아이디\r\n");
      out.write("         var ai_log_mem_id = \"\"; // 고객 아이디\r\n");
      out.write("         var ai_log_mobile_web_yn = \"0\"; // 모바일웹 이라면 1, 데스크탑 홈페이지라면 0\r\n");
      out.write("         var ai_log_app_conn_yn = \"0\"; // 하이브리드 앱이라면 1, 아닌경우 0\r\n");
      out.write("         var ai_log_page_title = \"한끼맛있다\"; // 페이지 제목\r\n");
      out.write("         var ai_log_page_url = \"./main\"; // 페이지 url, 빈값 입력시 브라우져 url 자동 입력 입니다.\r\n");
      out.write("         var ai_log_event_mode = \"\"; // board_reg:게시글 작성, mem_reg:회원가입, sale:매출발생  (default:빈칸)\r\n");
      out.write("         var ai_log_event_sale_price = \"\"; // ai_log_event_mode가 sale 일때  매출 금액\r\n");
      out.write("         </script>\r\n");
      out.write("                     <script type=\"text/javascript\" id=\"ai_log_chk_script\"></script>\r\n");
      out.write("            <script type=\"text/javascript\" id=\"ai_log_default_script\" src=\"./chk101.ai-log.biz/etc/connect_ai_set.js?ver=1\"></script>\r\n");
      out.write("                     </head>\r\n");
      out.write("\r\n");
      out.write("      <body >\r\n");
      out.write("<div  >\r\n");
      out.write("<!-- ---------------  layout : 2칸 레이아웃 : 182959 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_182959_ grid_13\">\r\n");
      out.write("   <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 로고 A : 182961  --------------- -->\r\n");
      out.write("<div   style='text-align:center;'  ><!-- 로고 A -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"logo_182961_\">\r\n");
      out.write("   <h1><a href=\"./\" target=\"_self\"><img src=\"./hanki/img_up/shop_pds/ehompy0118/farm/logo1519610629.jpg\" alt=\"로고\"></a></h1>\r\n");
      out.write("   <a href=\"javascript:alert('스마트폰에서만 전화를 연결할 수 있습니다.');\"class=\"toggle_182961_ tel_182961_\">전화걸기</a>\r\n");
      out.write("   <a href=\"#\" id=\"farmToggleSearch\" class=\"toggle_182961_ toggleSearch_182961_\">토글 검색</a>\r\n");
      out.write("   <a href=\"#\" id=\"farmToggleGnb\" class=\"toggle_182961_ toggleGnb_182961_\">토글 상단로그인</a>\r\n");
      out.write("   <a href=\"#\" id=\"farmToggleLnb\" class=\"toggle_182961_ toggleLnb_182961_\">토글 네비게이션</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(function($){\r\n");
      out.write("   // toggle contents plugin\r\n");
      out.write("   $.fn.toggleContents = function($target, $group)\r\n");
      out.write("   {\r\n");
      out.write("      $(this).on('click', function(){\r\n");
      out.write("         $(this).siblings('[id^=farmToggle]').removeClass('on');\r\n");
      out.write("         $(this).toggleClass('on');\r\n");
      out.write("         $('[id^=farmBox].on').each(function(){\r\n");
      out.write("            if($(this).attr('id')!=$target.attr('id')){\r\n");
      out.write("               $(this).removeClass('on').removeAttr('style');\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("         $target.slideToggle(200, function(){\r\n");
      out.write("            $target.toggleClass('on').removeAttr('style');\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("         return false;\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   if($('#farmBoxSearch').length){\r\n");
      out.write("      $('#farmToggleSearch').addClass('use');\r\n");
      out.write("      $('#farmToggleSearch').toggleContents($('#farmBoxSearch'));\r\n");
      out.write("   }\r\n");
      out.write("   if($('#farmBoxGnb').length){\r\n");
      out.write("      $('#farmToggleGnb').addClass('use');\r\n");
      out.write("      $('#farmToggleGnb').toggleContents($('#farmBoxGnb'));\r\n");
      out.write("   }\r\n");
      out.write("   if($('#farmBoxLnb').length){\r\n");
      out.write("      $('#farmToggleLnb').addClass('use');\r\n");
      out.write("      $('#farmToggleLnb').toggleContents($('#farmBoxLnb'));\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</div></div>\r\n");
      out.write("   <div class=\"container_2\">\r\n");
      out.write("<!-- ---------------   layout in : 네비게이션 A : 182960  --------------- -->\r\n");
      out.write("<div   style='margin-top:30px;margin-bottom:20px;'  ><!-- 네비게이션 A -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"farmBoxLnb\" class=\"lnb_182960_\">\r\n");
      out.write("   <!-- 1 Depth -->\r\n");
      out.write("   <ul class=\"dep1\">\r\n");
      out.write("                  <li class=\" first has_sub\">\r\n");
      out.write("         <a href=\"./hanki/page/sub1_3.yu\" target=\"_self\">About</a>\r\n");
      out.write("         <div>\r\n");
      out.write("            <!-- 2 Depth -->\r\n");
      out.write("            <ul class=\"dep2\">\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub1_3.yu\" target=\"_self\">한끼맛있다 소개</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub1_4.yu\" target=\"_self\">오시는길</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("            <!-- // 2 Depth -->\r\n");
      out.write("         </div>      </li>\r\n");
      out.write("                  <li class=\" has_sub\">\r\n");
      out.write("         <a href=\"./hanki/page/sub2_1.yu\" target=\"_self\">MENU</a>\r\n");
      out.write("         <div>\r\n");
      out.write("            <!-- 2 Depth -->\r\n");
      out.write("            <ul class=\"dep2\">\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_10.yu\" target=\"_self\">Diener Set Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_2.yu\" target=\"_self\">Lunch Set Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_1.yu\" target=\"_self\">Main Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_4.yu\" target=\"_self\">Rice Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_3.yu\" target=\"_self\">Pasta Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_5.yu\" target=\"_self\">Pizza Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/out.yu\" target=\"_self\">Salad/Drink Menu</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("            <!-- // 2 Depth -->\r\n");
      out.write("         </div>      </li>\r\n");
      out.write("                  <li class=\" has_sub\">\r\n");
      out.write("         <a href=\"./hanki/page/sub2_6.yu\" target=\"_self\">Franchise</a>\r\n");
      out.write("         <div>\r\n");
      out.write("            <!-- 2 Depth -->\r\n");
      out.write("            <ul class=\"dep2\">\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_6.yu\" target=\"_self\">개설절차</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_7.yu\" target=\"_self\">개설비용</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub22.yu\" target=\"_self\">개설수익률</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/myreg/qna.yu\" target=\"_self\">1:1고객상담</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("            <!-- // 2 Depth -->\r\n");
      out.write("         </div>      </li>\r\n");
      out.write("                  <li class=\" has_sub\">\r\n");
      out.write("         <a href=\"./hanki/page/sub1_7.yu\" target=\"_self\">Store</a>\r\n");
      out.write("         <div>\r\n");
      out.write("            <!-- 2 Depth -->\r\n");
      out.write("            <ul class=\"dep2\">\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/myboard/cp368638.yu\" target=\"_self\">매장찾기</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/page/sub4_1.yu\" target=\"_self\">매장둘러보기</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("            <!-- // 2 Depth -->\r\n");
      out.write("         </div>      </li>\r\n");
      out.write("                  <li class=\" has_sub\">\r\n");
      out.write("         <a href=\"./hanki/bbs/hh1.yu\" target=\"_self\">News/Notice</a>\r\n");
      out.write("         <div>\r\n");
      out.write("            <!-- 2 Depth -->\r\n");
      out.write("            <ul class=\"dep2\">\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/bbs/hh1.yu\" target=\"_self\">News</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                             <li>\r\n");
      out.write("                  <a href=\"./hanki/bbs/news.yu\" target=\"_self\">공지사항</a>\r\n");
      out.write("               </li>\r\n");
      out.write("                           <li>\r\n");
      out.write("\t\t\t\t  <a href=\"./BoardList.bo\" target=\"_self\">자유게시판</a>\r\n");
      out.write("\t\t\t   </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- // 2 Depth -->\r\n");
      out.write("\t\t\t</div>\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"last has_sub\">\r\n");
      out.write("\t\t\t<a href=\"./hanki/page/sub3_1.yu\" target=\"_self\">Reservation</a>\r\n");
      out.write("\t\t\t\t\t<div>\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"dep2\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./hanki/page/sub3_1.yu\" target=\"_self\">예약하기</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"./hanki/page/sub3_2.yu\" target=\"_self\">예약확인</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\t\t</li>\r\n");
      out.write("   <!-- // 1 Depth -->\r\n");
      out.write("</div>\r\n");
      out.write("</div></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- ---------------    body content : 57327 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------    배너관리 - 이미지 슬라이드 (확장형) : 57297 --------------- -->\r\n");
      out.write("<div  >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"owl__57297_\" class=\"owl-carousel\">\r\n");
      out.write("         <div class=\"item\" data-hash=\"_57297__item0\">\r\n");
      out.write("               <img src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu11519619214.jpg\"\r\n");
      out.write("             data-src-m=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu11519619214.jpg\"\r\n");
      out.write("               data-src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu11519619214.jpg\"\r\n");
      out.write("                alt=\"\" class=\"main_img\">                  </div>\r\n");
      out.write("         <div class=\"item\" data-hash=\"_57297__item1\">\r\n");
      out.write("               <img src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu21519619225.jpg\"\r\n");
      out.write("                data-src-m=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu21519619225.jpg\"\r\n");
      out.write("                 data-src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu21519619225.jpg\"\r\n");
      out.write("                  alt=\"\" class=\"main_img\">                  </div>\r\n");
      out.write("         <div class=\"item\" data-hash=\"_57297__item2\">\r\n");
      out.write("               <img src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu31519619236.jpg\"\r\n");
      out.write("                data-src-m=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu31519619236.jpg\"\r\n");
      out.write("                 data-src=\"./hanki/img_up/shop_pds/ehompy0118/contents/banner/me-in-seul-ra-i-deu31519619236.jpg\" \r\n");
      out.write("                 alt=\"\" class=\"main_img\">                  </div>\r\n");
      out.write("   </div>\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(function($) {\r\n");
      out.write("   $('#owl__57297_').owlCarousel({\r\n");
      out.write("      margin: 0,                        // 이미지 간격\r\n");
      out.write("      loop: true,                        // 무한 반복\r\n");
      out.write("      center: false,                     // 액티브 슬라이드 가운데 정렬\r\n");
      out.write("      mouseDrag: true,                  // 마우스 드레그 사용\r\n");
      out.write("      touchDrag: true,                  // 터치 드레그 사용\r\n");
      out.write("      stagePadding: 0,                  // 스테이지 여백 (좌우 슬라이드 노출)\r\n");
      out.write("      nav: false,               // 방향 네비게이션\r\n");
      out.write("      dots: true,               // 하단 네비게이션\r\n");
      out.write("      dotsEach: false,                  // 하단 네비게이션 (페이지별 출력,항목별 출력)\r\n");
      out.write("      autoplay: true,                     // 자동 재생\r\n");
      out.write("      smartSpeed: 250,                  // 슬라이드 속도\r\n");
      out.write("      responsiveRefreshRate: 200,            // 반응형 체크 시간\r\n");
      out.write("      startPosition: 0,                  // 시작 슬라이드 번호\r\n");
      out.write("      URLhashListener: false,               // #URL 로 액티브 슬라이드 동작\r\n");
      out.write("      autoplayHoverPause: false,            // 마우스 오버시 일시정지\r\n");
      out.write("      responsiveClass: false,               // 반응형 class명 사용 (owl-reponsive-0)\r\n");
      out.write("      navContainer: false,               // 방향 네비게이션 커스터마이징\r\n");
      out.write("      dotsContainer: false,               // 하단 네비게이션 커스터마이징\r\n");
      out.write("      items:1,                        // 한 화면 출력수\r\n");
      out.write("      slideBy:1,                        // 한번에 슬라이드 되는 수\r\n");
      out.write("      animateOut: 'fadeOut'   // 슬라이드(''), 페이드(fadeOut)\r\n");
      out.write("   })\r\n");
      out.write("\r\n");
      out.write("   changeImg();\r\n");
      out.write("\r\n");
      out.write("   $(window).on('resize',function(){\r\n");
      out.write("      changeImg();\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function changeImg(){\r\n");
      out.write("   if(Modernizr.mq('only all and (min-width:1024px)')==true){\r\n");
      out.write("      $('#owl__57297_').find('.main_img').each(function(){\r\n");
      out.write("         $(this).attr('src',$(this).attr('data-src'));\r\n");
      out.write("      });\r\n");
      out.write("   }else{\r\n");
      out.write("      $('#owl__57297_').find('.main_img').each(function(){\r\n");
      out.write("         $(this).attr('src',$(this).attr('data-src-m'));\r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ---------------    이미지 : 183800 --------------- -->\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------    공백 : 57634 --------------- -->\r\n");
      out.write("<!-- 공백 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"empty_line_57634_\"></span>\r\n");
      out.write("<div  >\r\n");
      out.write("<!-- ---------------  layout : 2칸 레이아웃 : 57628 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_57628_\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 타이틀 텍스트 : 57630  --------------- -->\r\n");
      out.write("<div   style='margin-left:3px;margin-right:3px;background-Color:#4C4C4C;text-align:center;'  ><!-- 타이틀 텍스트 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"title_57630_ style_none\">\r\n");
      out.write("   <p>한끼맛있다 메뉴안내</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ---------------   layout in : 공백 : 57311  --------------- -->\r\n");
      out.write("<div   style='margin-left:3px;margin-right:3px;background-Color:#4C4C4C;'  ><!-- 공백 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"empty_line_57311_\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ---------------   layout in : 공백 : 183842  --------------- -->\r\n");
      out.write("<div   style='margin-left:3px;margin-right:3px;'  ><!-- 공백 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"empty_line_183842_\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ---------------   layout in : 바둑판형태 이미지출력(반응형) : 57627  --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"pm-banner_responsive__57627_\">\r\n");
      out.write("   <ul>\r\n");
      out.write("                  <li class=\"item  m_clear t_clear p_clear\">\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_10.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/f4a4f7540dc18e808dc61e9926df2ef3_water__c1_w130_h200.jpg\" alt=\"dinner set menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item \">\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_2.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/3fe8f2bd07020a69e380a31e4cd2ec2d_water__c1_w130_h200.jpg\" alt=\"lunch set menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item  m_clear\">\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_1.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/8a90b3478e36751ed1d6513ce6540c3d_water__c1_w130_h200.jpg\" alt=\"main menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item  t_clear\">\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_4.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/864899ca43f05da453889b930ee6c710_water__c1_w130_h200.jpg\" alt=\"fusion rise menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item  m_clear\">\r\n");
      out.write("                  <a href=\"./page/sub2_3.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/a88c69b9c1cc1761d9fa44647efbf242_water__c1_w130_h200.jpg\" alt=\"fusion pasta menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item \">\r\n");
      out.write("                  <a href=\"./hanki/page/sub2_5.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/0f86f903568a806d6fb9c2e690ea6f63_water__c1_w130_h200.jpg\" alt=\"fusion pizza menu\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                  <li class=\"item  m_clear t_clear\">\r\n");
      out.write("                  <a href=\"./hanki/page/out.yu\">\r\n");
      out.write("                     <img src=\"./hanki/thum_img/ehompy0118/banner/4d697183a5cbebf6458767f55033cc1b_water__c1_w130_h200.jpg\" alt=\"salsd&drink\">                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("      <div class=\"container_2\">\r\n");
      out.write("<!-- ---------------   layout in : 이미지 (비율형) : 57629  --------------- -->\r\n");
      out.write("<!-- 이미지 (비율형) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"img_ratio_57629_\">\r\n");
      out.write("         <img src=\"./hanki/thum_img/ehompy0118/farm/9afcd07661081e3b7131ffc61953e613_water__c1_w240_h238.jpg\" alt=\"이미지명\">\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- ---------------    공백 : 183844 --------------- -->\r\n");
      out.write("<div  ><!-- 공백 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"empty_line_183844_\"></span>\r\n");
      out.write("</div><div  >\r\n");
      out.write("<!-- ---------------  layout : 3칸 레이아웃 : 57632 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_57632_\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 이미지 (비율형) : 57633  --------------- -->\r\n");
      out.write("<!-- 이미지 (비율형) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"img_ratio_57633_\">\r\n");
      out.write("      <a href=\"./hanki/page/sub1_7.yu\" target=\"_self\">\r\n");
      out.write("         <img src=\"./hanki/thum_img/ehompy0118/farm/753b7455e70144241efef3d570f80988_water__c1_w370_h200.jpg\" alt=\"매장찾기\">\r\n");
      out.write("      </a>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("      <div class=\"container_2\">\r\n");
      out.write("<!-- ---------------   layout in : 이미지 (비율형) : 57638  --------------- -->\r\n");
      out.write("<!-- 이미지 (비율형) -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"img_ratio_57638_\">\r\n");
      out.write("         <img src=\"./hanki/thum_img/ehompy0118/farm/7178c3ccc2b9174209214f5ca61741d1_water__c1_w370_h200.jpg\" alt=\"매장찾기\" width=\"370\" height=\"200\" usemap=\"#Map\" border=\"0\"/>\r\n");
      out.write("<map name=\"Map\" id=\"Map\">\r\n");
      out.write("  <area shape=\"rect\" coords=\"50,135,92,175\" href=\"https://www.facebook.com/\" target=\"blank\" />\r\n");
      out.write("  <area shape=\"rect\" coords=\"126,135,168,176\" href=\"https://twitter.com/\" target=\"blank\"/>\r\n");
      out.write("  <area shape=\"rect\" coords=\"196,135,244,176\" href=\"https://www.instagram.com/\" target=\"blank\"/>\r\n");
      out.write("  <area shape=\"rect\" coords=\"272,134,315,177\" href=\"https://story.kakao.com/s/login\" target=\"blank\"/>\r\n");
      out.write("</map>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("      <div class=\"container_3\">\r\n");
      out.write("<!-- ---------------   layout in : 최근 게시글 탭 - 웹진 + 목록형 (반응형) : 57631  --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"tab__57631_\" class=\"tab-board-extract-list pm-board_tab_webzine_list__57631_\">\r\n");
      out.write("      <div class=\"tab-wrap\">\r\n");
      out.write("      <ul class=\"tab-btn tab_col2\">\r\n");
      out.write("                     <li class=\"on\"><a href=\"#extract-list1-_57631_\">News</a></li>\r\n");
      out.write("                     <li class=\"\"><a href=\"#extract-list2-_57631_\">Notice</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("               <div id=\"extract-list1-_57631_\" class=\"tab-cont on\">\r\n");
      out.write("         <ul>\r\n");
      out.write("                                          <li class=\"webzine\">\r\n");
      out.write("                  <a href=\"./hanki/bbs_shop/read.htm?board_code=hh1&idx=276757&cate_sub_idx=0\">\r\n");
      out.write("                     <div class=\"thumnail\">\r\n");
      out.write("                        <img src=\"./hanki/thum_img/ehompy0118/2018/53c646668eab6e96b91b13116825ea1d_water__c1_w100_h100.jpg\" alt=\"맛과 가성비를 고루 갖춘 한끼맛있다 퓨전레스토랑이 드디어' 울산삼산동'에도 생겼다아!! \">\r\n");
      out.write("                     </div>                     <div class=\"title\">\r\n");
      out.write("                        맛과 가성비를 고루 갖춘 한끼맛있다 퓨전레스토랑이 드디어' 울산삼산동'에도 생겼다아!!                                                                      </div>\r\n");
      out.write("                     <div class=\"date\">2018-04-10</div>\r\n");
      out.write("                                          <!--<div class=\"body\">한끼맛있다 울산삼산점 04월 07일 grand open.!!!\r\n");
      out.write("울산에 한끼맛있다 삼산점이 오픈하였습니다. 한끼맛있다의 푸짐하고 맛있는 요리를 삼산동에서도 만나보실 수 있습니다.\r\n");
      out.write("부추통삼겹스테이크, 찹스테이크, 단호박불고기, 게살크림까르보나라,마약옥수수피자 등 다양한 셋트로 구성되어 있어 가성비최고 입니다.\r\n");
      out.write("가족, 연인, 친구,모임 등 삼산점에서 맛있는 ...</div>-->\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                          <li class=\"list\">\r\n");
      out.write("                  <a href=\"./hanki/bbs_shop/read.htm?board_code=hh1&idx=275597&cate_sub_idx=0\">\r\n");
      out.write("                                          <div class=\"title\">\r\n");
      out.write("                        한끼맛있다 울산삼산점 04월초 GRAND OPEN!!                                                                     </div>\r\n");
      out.write("                     <div class=\"date\">2018-03-14</div>\r\n");
      out.write("                                          <!---->\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                 </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("               <div id=\"extract-list2-_57631_\" class=\"tab-cont \">\r\n");
      out.write("         <ul>\r\n");
      out.write("                                          <li class=\"webzine\">\r\n");
      out.write("                  <a href=\"./hanki/bbs_shop/read.htm?board_code=news&idx=267272&cate_sub_idx=0\">\r\n");
      out.write("                     <div class=\"thumnail\">\r\n");
      out.write("                        <img src=\"./hanki/thum_img/ehompy0118/2017/2ed25db98e3ef10faeb6a3a9226807b7_water__c1_w100_h100.jpg\" alt=\"[대구월성점] 한끼맛있다 오픈준비중. (12월초오픈)\">\r\n");
      out.write("                     </div>                     <div class=\"title\">\r\n");
      out.write("                        [대구월성점] 한끼맛있다 오픈준비중. (12월초오픈)                                                                     </div>\r\n");
      out.write("                     <div class=\"date\">2017-10-28</div>\r\n");
      out.write("                                          <!--<div class=\"body\">한끼맛있다 대구월성점이 인테리어 공사중으로 12월초 오픈준비중입니다.</div>-->\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                          <li class=\"list\">\r\n");
      out.write("                  <a href=\"./hanki/bbs_shop/read.htm?board_code=news&idx=265054&cate_sub_idx=0\">\r\n");
      out.write("                                          <div class=\"title\">\r\n");
      out.write("                        대구성서점 11월 중순 오픈준비중 (인테리어공사착공)                                                                     </div>\r\n");
      out.write("                     <div class=\"date\">2017-09-28</div>\r\n");
      out.write("                                          <!---->\r\n");
      out.write("                  </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                                 </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(function($){\r\n");
      out.write("   $('#tab__57631_ .tab-btn a').on('mouseenter click',function(){\r\n");
      out.write("      var href= $(this).attr('href')\r\n");
      out.write("      if ($(this).parents('li').hasClass('on') == false) {\r\n");
      out.write("         $(href).addClass('on').siblings('.tab-cont').removeClass('on');\r\n");
      out.write("         $(this).parents('li').addClass('on').siblings('li').removeClass('on');\r\n");
      out.write("         return false;\r\n");
      out.write("      }\r\n");
      out.write("      return false;\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- ---------------    공백 : 57299 --------------- -->\r\n");
      out.write("<div  ><!-- 공백 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span class=\"empty_line_57299_\"></span>\r\n");
      out.write("</div><!-- ---------------  layout : 1칸 레이아웃 : 183819 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_183819_\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 최근 게시글 탭 - 웹진 + 목록형 (반응형) : 58595  --------------- -->\r\n");
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ---------------    아이콘 버튼 : 184656 --------------- -->\r\n");
      out.write("<div   style='background-Color:#f3f3f3;'  >\r\n");
      out.write("<!-- ---------------  layout : 1칸 레이아웃 : 57330 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_57330_\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 하단 메뉴 : 57331  --------------- -->\r\n");
      out.write("<div   style='margin-top:5px;margin-bottom:3px;text-align:center;'  ><!-- 하단 메뉴 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"fnb_57331_\">\r\n");
      out.write("   <ul>\r\n");
      out.write("               <li><a href=\"./hanki/shop_info/privacy.yu\">개인정보취급방침</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/shop_info/agree.yu\">이용약관</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/page/sub1_3.yu\" target=\"_self\">한끼맛있다 소개</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/page/sub2_6.yu\" target=\"_self\">개설절차</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/myboard/cp368638.yu\" target=\"_self\">매장찾기</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/page/sub1_4.yu\" target=\"_self\">오시는길</a></li>\r\n");
      out.write("               <li><a href=\"./hanki/page/sub2_1.yu\" target=\"_self\">MENU</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("   </nav>\r\n");
      out.write("</div></div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><div   style='background-Color:#5f5a58;' >\r\n");
      out.write("<!-- ---------------  layout : 1칸 레이아웃 : 58204 --------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"layout_58204_\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <div class=\"container_1\">\r\n");
      out.write("<!-- ---------------   layout in : 하단 정보 : 58205  --------------- -->\r\n");
      out.write("<div   style='margin-top:20px;margin-bottom:20px;text-align:center;'  ><!-- 하단 정보 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer_info_58205_\">\r\n");
      out.write("   <ul>\r\n");
      out.write("      <li>(주)쉐프마인드</li>      <li>대표자: 김성일, 김성수</li>      <li>사업자 등록번호: 585-86-00368 <!--<a href=\"javascript:popup_window('http://www.ftc.go.kr/info/bizinfo/communicationViewPopup.jsp?wrkr_no=1674800116',750,700)\" class=\"bizinfo\">사업자정보확인</a>--></li>      <li>주소: 부산광역시 부산진구 동천로 136, 3층 (전포동)  </li>      <li>TEL. 1899-6731</li>      <li>FAX. 051-803-0423</li>      <li>.</li>\r\n");
      out.write("         </ul>\r\n");
      out.write("   <ul>\r\n");
      out.write("      <li>Copyright(c) (주)쉐프마인드. All Rights Reserved. </li>\r\n");
      out.write(" <li><a href=\"http://www.ehompy.co.kr/\" target=\"_blank\"> <font color=\"#000\"><b>Homepage by 이홈피넷 </b></font></a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div></div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- ---------------    상단으로 바로가기 버튼 : 57334 --------------- -->\r\n");
      out.write("<div   style='text-align:right;'  ><!-- 상단으로 바로가기 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(window).on('scroll', function(){\r\n");
      out.write("   if ($(this).scrollTop() > 300){\r\n");
      out.write("      $('.scroll_top_57334_').addClass('on');\r\n");
      out.write("   }else{\r\n");
      out.write("      $('.scroll_top_57334_').removeClass('on');\r\n");
      out.write("   }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("jQuery(function($){\r\n");
      out.write("   $('.scroll_top_57334_').click(function() {\r\n");
      out.write("      $('body,html').animate({\r\n");
      out.write("         scrollTop: 0\r\n");
      out.write("      }, 800);\r\n");
      out.write("      return false;\r\n");
      out.write("   });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"scroll_top_57334_\">\r\n");
      out.write("   <span>상단으로 바로가기</span>\r\n");
      out.write("</div>\r\n");
      out.write("</div><script type=\"text/javascript\" src=\"./hanki/js/all_bottom_script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("all_page_script('','','','','','','','','0');\r\n");
      out.write("</script>\r\n");
      out.write("                  <script type=\"text/javascript\">\r\n");
      out.write("                     var event_win13383 = window.open('./hanki/shop_main/popup_window.htm?idx=13383','event_win13383','top=50,left=150,width=450,height=640,toolbar=no,scrollbars=no,resizable=no,fullscreen=no');\r\n");
      out.write("                     // 익스 팝업창 차단으로 인해 오류가 있을 수 있으므로 주석 처리 한다.\r\n");
      out.write("                     // event_win13383.focus();\r\n");
      out.write("                  </script>\r\n");
      out.write("                  \r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("      setTimeout(\"create_iframe(0,'ok_frame');\",100);\r\n");
      out.write("      setTimeout(\"create_iframe(0,'ok_frame2');\",100);\r\n");
      out.write("      </script>\r\n");
      out.write("      </body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
